name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build_unit_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build and test with Gradle
      run: ./gradlew build test

  android_tests:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 36
          arch: x86
          disable-animations: true
          script: ./gradlew connectedAndroidTest --stacktrace
